# Cloudflare Pages configuration

[build]
command = "npm run build:cloudflare"
publish = ".next"

[build.environment]
NODE_VERSION = "18"

[build.processing]
skip = true

[[redirects]]
from = "/_next/*"
to = "/_next/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
