[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "next dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
