# Cloudflare Pages configuration
[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

# Specify the directory to deploy
[site]
pages_build_output_dir = ".next"

# Enable Node.js compatibility
[build.processing]
skip_processing = true
